#!/usr/bin/env python3
"""Reproduce the pinned FreeDOS boot-code fragments from vendored ms-sys headers."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VENDOR = ROOT / "vendor" / "ms-sys"
OUTPUT = ROOT / "internal" / "freedos" / "bootassets"


@dataclass(frozen=True)
class Asset:
    source: str
    output: str


ASSETS = (
    Asset("mbr_rufus.h", "rufus-mbr-code.bin"),
    Asset("br_fat32_0x0.h", "fat32-freedos-pbr-0x0.bin"),
    Asset("br_fat32fd_0x52.h", "fat32-freedos-pbr-0x52.bin"),
    Asset("br_fat32fd_0x3f0.h", "fat32-freedos-pbr-0x3f0.bin"),
)

ARRAY_RE = re.compile(
    r"unsigned\s+char\s+[A-Za-z_][A-Za-z0-9_]*\s*\[\s*\]\s*=\s*\{(?P<body>.*?)\};",
    re.DOTALL,
)
HEX_RE = re.compile(r"0x([0-9A-Fa-f]{1,2})")


def extract_array(path: Path) -> bytes:
    text = path.read_text(encoding="utf-8")
    matches = list(ARRAY_RE.finditer(text))
    if len(matches) != 1:
        raise ValueError(f"{path}: expected exactly one unsigned-char array, found {len(matches)}")
    values = bytes(int(value, 16) for value in HEX_RE.findall(matches[0].group("body")))
    if not values:
        raise ValueError(f"{path}: byte array is empty")
    return values


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def check_asset(asset: Asset, expected: bytes) -> None:
    output = OUTPUT / asset.output
    try:
        actual = output.read_bytes()
    except FileNotFoundError as exc:
        raise ValueError(f"missing generated asset: {output}") from exc
    if actual != expected:
        raise ValueError(
            f"{output}: generated bytes differ from {asset.source}; "
            f"expected sha256 {digest(expected)}, got {digest(actual)}"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed binaries instead of rewriting them",
    )
    args = parser.parse_args()

    try:
        generated = [(asset, extract_array(VENDOR / asset.source)) for asset in ASSETS]
        if args.check:
            for asset, data in generated:
                check_asset(asset, data)
        else:
            OUTPUT.mkdir(parents=True, exist_ok=True)
            for asset, data in generated:
                (OUTPUT / asset.output).write_bytes(data)
    except (OSError, ValueError) as exc:
        print(f"FreeDOS boot-asset extraction failed: {exc}", file=sys.stderr)
        return 1

    for asset, data in generated:
        print(f"{asset.output}: {len(data)} bytes sha256={digest(data)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
