#!/usr/bin/env python3
"""Generate the deterministic RufusArm64 primary-UI gettext template."""

import argparse
import ast
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "gui" / "rufusarm64_i18n.py"
OUTPUT = ROOT / "po" / "rufusarm64.pot"
SOURCE_REFERENCE = "gui/rufusarm64_i18n.py"


def collect_messages(source_text):
    tree = ast.parse(source_text, filename=str(SOURCE))
    messages = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Name) or node.func.id != "N_":
            continue
        if len(node.args) != 1 or node.keywords:
            raise ValueError(f"N_ marker at line {node.lineno} must contain exactly one positional string")
        value = ast.literal_eval(node.args[0])
        if not isinstance(value, str) or not value:
            raise ValueError(f"N_ marker at line {node.lineno} must contain a non-empty string")
        messages.add(value)
    if not messages:
        raise ValueError("no N_ translation markers were found")
    return messages


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def render(messages):
    lines = [
        "# RufusArm64 primary GTK interface translation template.",
        "# Generated by scripts/update-pot.py; do not edit by hand.",
        "msgid \"\"",
        "msgstr \"\"",
        quote("Project-Id-Version: RufusArm64\\n"),
        quote("Report-Msgid-Bugs-To: https://github.com/geocausa/RufusUbuntuArm64/issues\\n"),
        quote("MIME-Version: 1.0\\n"),
        quote("Content-Type: text/plain; charset=UTF-8\\n"),
        quote("Content-Transfer-Encoding: 8bit\\n"),
        quote("Plural-Forms: nplurals=2; plural=(n != 1);\\n"),
        "",
    ]
    for message in sorted(messages):
        lines.extend((f"#: {SOURCE_REFERENCE}", f"msgid {quote(message)}", "msgstr \"\"", ""))
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the checked-in template differs")
    args = parser.parse_args(argv)

    try:
        rendered = render(collect_messages(SOURCE.read_text(encoding="utf-8")))
    except (OSError, SyntaxError, ValueError) as exc:
        print(f"could not generate gettext template: {exc}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"gettext template is missing: {exc}", file=sys.stderr)
            return 1
        if current != rendered:
            print("po/rufusarm64.pot is stale; run scripts/update-pot.py", file=sys.stderr)
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
